# Site settings
title: "Julia + David"
description: |
    Denver, Colorado

    August 12, 2018
owner: Laura Gerhardt
first_published: 2018
baseurl: "" # the subpath of your site, e.g. /blog
url: "juliaanddavid/wedding-site" # the base hostname & protocol for your site

social:
  github: https://github.com/juliaanddavid/wedding-site

# Build settings
markdown: kramdown
